/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#2b1707",
        "outline": "#717973",
        "background": "#fbf9f1",
        "surface-variant": "#e4e3db",
        "on-primary-fixed": "#002114",
        "outline-variant": "#c1c8c2",
        "on-primary-container": "#86af99",
        "on-primary": "#ffffff",
        "surface-tint": "#3f6653",
        "on-secondary-container": "#7a5d48",
        "surface-bright": "#fbf9f1",
        "on-background": "#1b1c17",
        "primary-fixed": "#c1ecd4",
        "primary": "#012d1d",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#ffdcc5",
        "tertiary-container": "#2a4131",
        "surface": "#fbf9f1",
        "surface-container-highest": "#e4e3db",
        "primary-fixed-dim": "#a5d0b9",
        "secondary-fixed-dim": "#e4bfa6",
        "surface-container-low": "#f5f4ec",
        "on-error-container": "#93000a",
        "on-surface": "#1b1c17",
        "on-secondary-fixed-variant": "#5b412e",
        "tertiary-fixed": "#cee9d3",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#092012",
        "on-tertiary-fixed-variant": "#354c3b",
        "on-surface-variant": "#414844",
        "surface-container-high": "#eae8e0",
        "on-tertiary-container": "#93ad98",
        "inverse-surface": "#30312c",
        "inverse-primary": "#a5d0b9",
        "secondary": "#755844",
        "surface-container": "#f0eee6",
        "primary-container": "#1b4332",
        "error": "#ba1a1a",
        "surface-dim": "#dcdad2",
        "on-error": "#ffffff",
        "secondary-container": "#ffd8be",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#b3cdb7",
        "inverse-on-surface": "#f3f1e9",
        "on-secondary": "#ffffff",
        "tertiary": "#152b1c",
        "on-primary-fixed-variant": "#274e3d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        "margin-mobile": "16px",
        gutter: "20px",
        base: "8px",
        "margin-desktop": "32px",
        md: "24px",
        xs: "4px",
        xl: "64px",
        lg: "40px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Sora"],
        "headline-lg": ["Sora"],
        "body-lg": ["Sora"],
        "label-md": ["Sora"],
        "headline-xl": ["Sora"],
        "body-md": ["Sora"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["20px", { lineHeight: "30px", fontWeight: "400" }],
        "label-md": ["16px", { lineHeight: "24px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
